version: '3.8'

services:
  web:
    build: ./container/apache
    container_name: web
    restart: always
    ports:
      - ${WEB_PORT}:80
    volumes:
      - ../:/var/www/html
      - ./container/apache/httpd.conf:/usr/local/apache2/conf/httpd.conf
    depends_on:
      - app

  app:
    build: ./container/php
    container_name: app
    restart: always
    volumes:
      - ../:/var/www/html
    working_dir: /var/www/html
    environment:
      COMPOSER_ALLOW_SUPERUSER: 1
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: db
    restart: always
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_ALLOW_EMPTY_PASSWORD: "no"
      MYSQL_RANDOM_ROOT_PASSWORD: "no"
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - ${DB_PORT}:3306

volumes:
  db-data:
    driver: local
